recipe_version: '2'
name: Qwen3.8-27B-NVFP4
model: RadixArk/Qwen3.8-27B-NVFP4
runtime: sglang
container: lmsysorg/sglang:dev-qwen38-27b-dflash2
command: |
  taskset -c 5-9,15-19 sglang serve --trust-remote-code --reasoning-parser qwen3 --tool-call-parser qwen3_coder --model-path {model} --host {host} --port {port} --tp {tensor_parallel} --context-length {context_length} --max-running-requests {max_num_seqs} --kv-cache-dtype {kv_cache_dtype} --chunked-prefill-size {chunked_prefill_size} --mem-fraction-static {gpu_memory_utilization} --attention-backend {attention_backend} --mamba-full-memory-ratio {mamba_full_memory_ratio} --mamba-radix-cache-strategy {mamba_radix_cache_strategy} --mamba-ssm-dtype {mamba_ssm_dtype} --speculative-algorithm {speculative_algorithm} --speculative-draft-model-path {speculative_draft_model} --speculative-num-draft-tokens {speculative_draft_tokens} --json-model-override-args '{"rope_scaling":{"rope_type":"yarn","factor":{rope_factor},"original_max_position_embeddings":{max_model_len}}}'
mods:
  - drop-caches
defaults:
  port: 8000
  host: 0.0.0.0
  tensor_parallel: 1
  gpu_memory_utilization: 0.8
  max_model_len: 262144
  max_num_seqs: 4
  attention_backend: flashinfer
  rope_factor: 4
  context_length: 1010000
  mamba_full_memory_ratio: 3.51
  mamba_ssm_dtype: bfloat16
  mamba_radix_cache_strategy: extra_buffer_lazy
  kv_cache_dtype: fp8_e4m3
  chunked_prefill_size: 4096
  speculative_algorithm: DFLASH
  speculative_draft_model: incoai/Qwen3.8-27B-DFlash2
  speculative_draft_tokens: 8
env:
  SGLANG_ALLOW_OVERWRITE_LONGER_CONTEXT_LEN: '1'
min_nodes: 1
metadata:
  description: Qwen3.8-27B-NVFP4-DFlash2
  maintainer: Little Cedar Group <sparkrun@littlecedar.net>
  model_params: 27B
  model_dtype: nvfp4
  model_draft_dtype: bf16
  kv_dtype: fp8_e4m3
  tags: lcg_favorite, fast, large-context
